import os
import subprocess
import sys

# Directory setup
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
INCLUDE_DIR = os.path.join(PROJECT_ROOT, "include", "overlay")
OUTPUT_HEADER = os.path.join(INCLUDE_DIR, "fonts.h")

# The fonts to process and their corresponding C array names
FONTS = [
    {"file": "main-ui.ttf", "array_name": "g_font_main_ui_data"},
    {"file": "mono.ttf", "array_name": "g_font_mono_data"},
    {"file": "notes-read.ttf", "array_name": "g_font_notes_read_data"},
]

# Unicodes to keep: 
# U+0020-007E (Basic Latin)
# U+00A0-00FF (Latin-1 Supplement - optional, but good for some basic symbols/extended chars)
# U+2000-206F (General Punctuation - good for quotes, dashes used in markdown)
UNICODE_RANGE = "U+0020-007E,U+00A0-00FF,U+2000-206F"

def subset_font(input_path, output_path):
    print(f"Subsetting {input_path}...")
    # Using pyftsubset from fonttools
    cmd = [
        sys.executable, "-m", "fontTools.subset",
        input_path,
        f"--unicodes={UNICODE_RANGE}",
        f"--output-file={output_path}",
        "--flavor=woff2", # We won't use woff2 because ImGui needs TTF.
    ]
    
    # Correct command for TTF output
    cmd = [
        sys.executable, "-m", "fontTools.subset",
        input_path,
        f"--unicodes={UNICODE_RANGE}",
        f"--output-file={output_path}",
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error subsetting {input_path}:\n{result.stderr}")
        return False
    return True

def convert_to_c_array(file_path, array_name):
    with open(file_path, "rb") as f:
        data = f.read()
        
    lines = []
    lines.append(f"const unsigned int {array_name}_size = {len(data)};")
    lines.append(f"const unsigned char {array_name}[{len(data)}] = {{")
    
    # Format bytes to hex
    hex_data = [f"0x{b:02x}" for b in data]
    
    # Group into lines of 12 bytes
    for i in range(0, len(hex_data), 12):
        chunk = hex_data[i:i+12]
        lines.append("    " + ", ".join(chunk) + ",")
        
    lines.append("};")
    return "\n".join(lines)

def main():
    if not os.path.exists(INCLUDE_DIR):
        os.makedirs(INCLUDE_DIR)
        
    header_content = [
        "#pragma once",
        "// Auto-generated by raw_fonts/build_fonts.py",
        "// Contains subsetted embedded TTF font data",
        "namespace dover::overlay {",
        ""
    ]
    
    for font in FONTS:
        input_path = os.path.join(SCRIPT_DIR, font["file"])
        temp_subset_path = os.path.join(SCRIPT_DIR, f"subset_{font['file']}")
        
        if not os.path.exists(input_path):
            print(f"Warning: {input_path} not found. Skipping.")
            continue
            
        if subset_font(input_path, temp_subset_path):
            c_array_str = convert_to_c_array(temp_subset_path, font["array_name"])
            header_content.append(c_array_str)
            header_content.append("")
            
            # Clean up temp file
            os.remove(temp_subset_path)
            
    header_content.append("} // namespace dover::overlay")
    
    with open(OUTPUT_HEADER, "w") as f:
        f.write("\n".join(header_content))
        
    print(f"Successfully generated {OUTPUT_HEADER}")

if __name__ == "__main__":
    main()
